### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by bdsoha** [liormorad/homebridge-vitrea#1]
Hello,

I have a *(privately hosted)* working **Vitrea** plugin for homebridge.
Have you made any progress on this?

**Comment by liormorad** [comment]
Hi,

So far - I reverse-engineered the protocol between the app and the router.
I guess I'll be resuming my work there in the next couple of weeks and actually write the plugin.

Please note that the Vitrea system I'm working on is the "legacy" one (I installed it 8 years ago),  everything's propriatery.
I think it's called "VTouch Classic" now.

Does your plugin work on this system ?

**Comment by bdsoha** [comment]
> Hi,
> 
> So far - I reverse-engineered the protocol between the app and the router. I guess I'll be resuming my work there in the next couple of weeks and actually write the plugin.
> 
> Please note that the Vitrea system I'm working on is the "legacy" one (I installed it 8 years ago), everything's propriatery. I think it's called "VTouch Classic" now.
> 
> Does your plugin work on this system ?

I already reverse engineered the protocol on both versions.
The protocol did not change that much, and yes, today its called *VTouch Classic*.

**Comment by liormorad** [comment]
> > Hi,
> > So far - I reverse-engineered the protocol between the app and the router. I guess I'll be resuming my work there in the next couple of weeks and actually write the plugin.
> > Please note that the Vitrea system I'm working on is the "legacy" one (I installed it 8 years ago), everything's propriatery. I think it's called "VTouch Classic" now.
> > Does your plugin work on this system ?
> 
> I already reverse engineered the protocol on both versions. The protocol did not change that much, and yes, today its called _VTouch Classic_.

Cool !
Do you plan to publish it ?
Would you like to join forces ? I might be able to help with coding / testing on my environment etc.
let me know.
Thanks

**Comment by bdsoha** [comment]
> > > Hi,
> > > So far - I reverse-engineered the protocol between the app and the router. I guess I'll be resuming my work there in the next couple of weeks and actually write the plugin.
> > > Please note that the Vitrea system I'm working on is the "legacy" one (I installed it 8 years ago), everything's propriatery. I think it's called "VTouch Classic" now.
> > > Does your plugin work on this system ?
> > 
> > 
> > I already reverse engineered the protocol on both versions. The protocol did not change that much, and yes, today its called _VTouch Classic_.
> 
> Cool ! Do you plan to publish it ? Would you like to join forces ? I might be able to help with coding / testing on my environment etc. let me know. Thanks

I have been hosting it privately for internal use for the past 7 years *(with a full re-write 3 years ago)*.
Contact me via email for more details.
